version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - my_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - my_network
    depends_on:
      - database

  database:
    image: alpine:latest
    volumes:
      - ./database:/db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
